### ISSUE TITLE
CURRENT_TIMESTAMP detection mistake

### ISSUE THREAD

**Issue by BCsabaEngine** [nwoltman/node-mysql-plus#4]
Used 10.3.22-MariaDB-0+deb10u1 (RaspberryPI) the DateTime field with CURRENT_TIMESTAMP modified in every run.
Reason: detected UpdatableTimeColumnDefinition._default = "current_timestamp()", but the target column definition is "CURRENT_TIMESTAMP". So it is a mysql/mariadb dialect difference. It may be NOW() in previous mysql (5.x?) versions.

TableDefinitions.js#line134: the comparer function should be smarter to handle dialect differences.

**Comment by nwoltman** [comment]
Hi @SymbolCsaba. I just wanted to acknowledge that I understand the issue and I think I know how it could be fixed, but I haven't found the time to work on the fix yet. I hope to be able to work on this sometime within the next few days.

**Comment by nwoltman** [comment]
This should be fixed in `v0.16.2`

**Comment by BCsabaEngine** [comment]
Works great, thank you!
